# Generated by Django 5.1.6 on 2025-03-20 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(choices=[('MA', 'Maestro'), ('AP', 'Apriori'), ('TE', 'Tezaur'), ('RO', 'Roua Moldovei'), ('JA', "J'Adore"), ('TA', 'Taiga')], max_length=2, verbose_name='Бренд')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фотография')),
            ],
        ),
    ]
