# Generated by Django 5.1.6 on 2025-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_alter_product_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(default='', max_length=32, verbose_name='Название категории'),
            preserve_default=False,
        ),
    ]
