# Generated by Django 5.1.6 on 2025-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_category_name_en_category_name_ro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_en'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'category', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='name_ro',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ro)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=32, verbose_name='Название категории (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=32, verbose_name='Название категории (ro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название (en)'),
        ),
    ]
