# Generated by Django 5.1.6 on 2025-03-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'category', 'name_en'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_en',
        ),
    ]
