# Generated by Django 5.1.6 on 2025-03-21 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_options_rename_name_product_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(choices=[('MA', 'Maestro'), ('AP', 'Apriori'), ('TE', 'Tezaur'), ('RO', 'Roua Moldovei'), ('JA', "J'Adore"), ('GL', 'Glenwood'), ('TA', 'Taiga')], max_length=2, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['brand', 'order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name_en', 'order'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand', verbose_name='Бренд'),
        ),
    ]
